apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: apache2
  name: apache2-service
  namespace: default
spec:
  ports: 
   - port: 80
     protocol: tcp
     targetPort: 80
  selector: 
    app: apache2
  type: NodePort
